### ISSUE TITLE
Clicking on a page thumbnail does not scroll main view

### ISSUE THREAD

**Issue by jazzido** [tabulapdf/tabula#712]
![tabula](https://user-images.githubusercontent.com/27584/29179657-259000fc-7dc3-11e7-999b-d3eeb4737d84.gif)

Not sure if this is also happening in `master`, tested in `tabula-java-1.0.0`.

**Comment by jeremybmerrill** [comment]
Oof -- this is an interaction of the <base> tag with anchor links... Might require some gross JS to fix.

**Comment by jeremybmerrill** [comment]
fixed in 5db236e; not as gross of a fix as I worried 5db236e

**Comment by jazzido** [comment]
w00t

**Comment by jazzido** [comment]
Hi @jeremybmerrill, this still happens when coming back from the results view. May be the event handlers are removed and not recreated when switching pages?

**Comment by jeremybmerrill** [comment]
Good catch. Fixed in 59fca1b (and you were right about the problem, btw :) ).
